#include "cpp_package_boilerplate/package.hpp"

#include <iostream>

/**
 * @brief Example CLI entry point for the template package.
 *
 * This binary demonstrates how an application can consume the library API.
 * It prints a greeting generated by `cpp_package_boilerplate::greet`.
 *
 * @return Exit status code. Returns `0` on success.
 */
int main() {
    std::cout << cpp_package_boilerplate::greet("world") << '\n';
    return 0;
}
