name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t cpp-package-boilerplate:latest .
